version: '3'

services:
  database:
    image: 'bitnami/mysql:latest'
    container_name: 'banco_de_dados'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - mysql_data:/bitnami/mysql/data
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
     build: .
     container_name: 'app'
     ports:
       - 5000:5000
     depends_on:
       database:
         condition: service_healthy
     networks:
       - app-network
     volumes:
       - .:/home/app
     environment:
        - FLASK_ENV=development

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
