-- Active: 1715605010850@@127.0.0.1@3306@bd
CREATE DATABASE IF NOT EXISTS `bd`;

USE DATABASE `bd`;

CREATE TABLE IF NOT EXISTS foto (
    id CHAR(36) DEFAULT(UUID()) PRIMARY KEY NOT NULL,
    imagem VARCHAR(255) DEFAULT 'default.png',
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_noticia CHAR(36),
    FOREIGN KEY (id_noticia) REFERENCES noticia (id)
);